# Generated by Django 5.1 on 2025-10-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrenamiento', models.CharField(help_text='Ej: Obediencia Básica, Agilidad, Guardia y Protección, Socialización, etc.', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del contenido del entrenamiento.', null=True)),
                ('fecha_inicio', models.DateField(help_text='Fecha en que comienza el entrenamiento.')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha estimada de finalización del entrenamiento (puede ser nula si es continuo).', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrenamiento de Perro',
                'verbose_name_plural': 'Entrenamientos de Perros',
                'ordering': ['fecha_inicio', 'tipo_entrenamiento'],
            },
        ),
    ]
